#!/bin/bash
echo "Usage: $0 [branch-name]"
echo "Make sure you are on master. No args describes all local branches"

URL="https://issues.apache.org/jira/browse/"
TMP=".tmp-bash-file"
BRANCH="$1"

if [[ -n "$BRANCH" ]] ; then
  echo "$BRANCH" > $TMP
else
  git branch | grep ACC* > $TMP
fi

while read -r line
  do FULL_URL="${URL}${line}"
  #echo "curling for $FULL_URL"
  echo -n "$line "
  curl -s $FULL_URL | grep "<title>" | sed 's|<[/]*title>||g' | sed 's|- ASF JIRA||g'
done < $TMP

rm $TMP
