#!/bin/bash
# Prunes origin and upstream then prompts to delete gone branches"

CURRENT=$(git rev-parse --abbrev-ref HEAD)
if [[ "$CURRENT" != "master" ]] ; then
	echo "Please switch to master"
	exit 1
fi
set -x #echo on

git remote prune origin
git remote prune upstream
{ set +x; } 2>/dev/null

CMD=`git branch -vv | grep gone | awk '{print $1}'`

echo "Delete these branches?"
echo "$CMD" 

read -p "(y/n): " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
    exit 1
fi
git branch -vv | grep gone | awk '{print $1}' | xargs git branch -D
