#!/bin/bash
set -x #echo on
. $SCRIPTS_HOME/mvn/maven-opts
env | grep MAVEN

TEST=$1
shift
mvn clean -Dit.test=$TEST -Dtest=foo -Dspotbugs.skip -Drat.skip -Dformatter.skip -Dcheckstyle.skip -Dmodernizer.skip -Dimpsort.skip -Dsortpom.skip -DfailIfNoTests=false "$@" verify

