#!/bin/bash
. $SCRIPTS_HOME/mvn/maven-opts
env | grep MAVEN

echo "mvn clean package -q -Dfindbugs.skip -DskipTests -DskipITs -Dcheckstyle.skip -l /tmp/mvn-build-out"
mvn clean package -q -Dfindbugs.skip -DskipTests -DskipITs -Dcheckstyle.skip -l /tmp/mvn-build-out

