#!/bin/bash
set -x #echo on
. $SCRIPTS_HOME/mvn/maven-opts
env | grep MAVEN

mvn clean package -Dspotbugs.skip -DskipTests -DskipITs -Dcheckstyle.skip -Drat.skip -Dformatter.skip -Dmodernizer.skip -Dimpsort.skip -Dsortpom.skip
