#!/bin/bash
. $SCRIPTS_HOME/mvn/maven-opts
env | grep MAVEN

TEST=$1
shift
echo "mvn clean -Dit.test=$TEST -Dtest=foo -Dfindbugs.skip -Dcheckstyle.skip -DfailIfNoTests=false \"$@\" verify"
mvn clean -Dit.test=$TEST -Dtest=foo -Dfindbugs.skip -Dcheckstyle.skip -DfailIfNoTests=false "$@" verify

