#!/bin/bash
. $SCRIPTS_HOME/mvn/maven-opts
env | grep MAVEN

echo "mvn clean package -Dfindbugs.skip -DskipTests -DskipITs -Drat.skip"
mvn clean package -Dfindbugs.skip -DskipTests -DskipITs -Drat.skip 

