#!/bin/bash
# usage: mvn-standaloneIT

#. $SCRIPTS_HOME/util.sh

CONF="accumulo-it.properties"
CONF_FILE="$ACCUMULO_HOME/conf/$CONF"

echo "Using conf file: $CONF_FILE"

#set -x #echo on
# mvn was crashing with Uno running
#. $SCRIPTS_HOME/mvn/maven-opts
#env | grep MAVEN

MVN="mvn clean verify -Dtest=foo -Dspotbugs.skip -Drat.skip -Dformatter.skip -Dcheckstyle.skip -Dmodernizer.skip -Dimpsort.skip -Dsortpom.skip -DfailIfNoTests=false -Dfailsafe.groups=org.apache.accumulo.test.categories.StandaloneCapableClusterTests -Daccumulo.it.properties=$CONF_FILE"
if [[ -f $CONF_FILE ]]; then
   echo "$MVN"
   eval $MVN
else
   echo "The config file $CONF_FILE aint there. ACCUMULO_HOME = $ACCUMULO_HOME"
fi
